import numpy
import math

lista = "CTAGCAGAAGAAGAGGTAGTAATTAGATCTGCCAATTTCACAGACAATGCTAAAATCATAATAGTACAGCTGAATGCATCTGTAGAAATTAATTGTACAAGGCCCAACAACAATACAAGAAAAGGTATACATATAGGACCAGGGAGAGCATTTTATGCAACAGGAGAAATAATAGGAGATATAAGACAAGCACATTGTAACATTAGTAGAGAAAAATGGAATAATACTTTAAACCAGGTAGTTACAGAATTAAGGGAACAATTTGGGAATAAAACAATAACCTTTAATCACTCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTTAATTGTGGAGGGGAATTTTTCTATTGTAAT"
listc = "CTAGCAGAAGAAGAGGTAGTAATTAGATCTGCCAATTTCACAGACAATGCTAAAATCATAATAGTACAGCTGAATGCATCTGTAGAAATTAATTGTACAAGGCCCAACAACAATACAAGAAAAGGTATACATATAGGACCAGGGAGAGCATTTTATGCAACAGGAGAAATAATAGGAGATATAAGACAAGCACATTGTAACATTAGTAGAGAAAAATGGAATAATACTTTAAACCAGGTAGTTACAGAATTAAGGGAACAATTTGGGAATAAAACAATAACCTTTAATCACTCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTTAATTGTGGAGGGGAATTTT"
listb = "CTAGCAGAAGAAGAGGTAGTAATTAGATCTGCCGATTTCACAGACAATGCTAAAATCATAATAGTACAGCTAAATGCATCTGTAGAAATTAATTGTACAAGACCTAACAACAATACAAGAAAAGGTATACATATAGGACCAGGGAGAGCAGTTTATGCAACAGACAGAATAATAGGAGATATAAGACAAGCACATTGTAACATTAGTAGAGAAAAATGGAATAATACTTTAAAACAGGTAGTTACAAAATTAAGAGAACAATTTGTGAATAAAACAATAATCTTTACTCACCCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTGTTAATTGTGGAGGGGAATTTT"
shorter = len(listb)

lista = lista[:shorter]

def calcDifference(seq1, seq2):
	difference = 0
	assert len(seq1) == len(seq2), 'sequences have to be the same length'
	for i in range(0, len(seq1)):
		if seq1[i] != seq2[i]:
			difference += 1
	perc_diff = float(difference) / float(len(seq1))
	inside_log = 1 - 4/3 * perc_diff
	return -0.75 * math.log(inside_log) 


fdsa = "ATTTCACAGACAATGCTAAAATCATAATAGTACAGCTGAATGCATCTGTAGAAATTAATTGTACAAGGCCCAACAACAATACAAGAAAAGGTATACATATAGGACCAGGGAGAGCATTTTATGCAACAGGAGAAATAATAGGAGATATAAGACAAGCACATTGTAACATTAGTAGAGAAAAATGGAATAATACTTTAAACCAGGTAGTTACAGAATTAAGGGAACAATTTGGGAATAAAACAATAACCTTTAATCACTCCTCAGGAGGGGACCCAGAAATTGTAATGCACA"
fdsb = "ATTTCACAGACAATGCTAAAATCATAATAGTACAGCTAAATGCATCTGTAGAAATTAATTGTACAAGACCTAACAACAATACAAGAAAAGGTATACATATAGGACCAGGGAGAGCAGTTTATGCAACAGACAGAATAATAGGAGATATAAGACAAGCACATTGTAACATTAGTAGAGAAAAATGGAATAATACTTTAAAACAGGTAGTTACAAAATTAAGAGAACAATTTGTGAATAAAACAATAATCTTTACTCACCCCTCAGGAGGGGACCCAGAAATTGTAATGCACA"

mat = numpy.zeros((5, 5))
mat[0, :] = numpy.array([0, 5, 9, 9, 8])
mat[1, :] = numpy.array([5, 0, 10, 10, 9])
mat[2, :] = numpy.array([9, 10, 0, 8, 7])
mat[3, :] = numpy.array([9, 10, 8, 0, 3])
mat[4, :] = numpy.array([8, 9, 7, 3, 0])

print mat[0]